// swift-tools-version: 6.2
import PackageDescription

// Stands in for a backend team's proto-contract repository: this package
// "publishes" eliza.proto (proto/eliza.proto, kept for reference/regeneration)
// plus the Swift models generated from it (Sources/ElizaProtoKit/Generated),
// committed rather than generated at build time — Tuist's Xcode project
// generation for locally-declared packages doesn't run SPM build tool
// plugins from a *different* external package, so SwiftProtobufPlugin isn't
// usable here; the generated file must be regenerated by hand (see README)
// whenever eliza.proto or the pinned swift-protobuf version changes.
// Client teams would normally add this via `.package(url: "https://github.com/
// <backend-team>/ElizaProtoKit.git", from: "1.0.0")` — here it's `.package(path:)`
// since everything lives in one repo, but the dependency mechanism is identical.
let package = Package(
    name: "ElizaProtoKit",
    platforms: [.iOS(.v26)],
    products: [
        .library(name: "ElizaProtoKit", targets: ["ElizaProtoKit"])
    ],
    dependencies: [
        // Vendored rather than fetched from apple/swift-protobuf directly —
        // see SwiftProtobufVendored/Package.swift for why.
        .package(path: "../SwiftProtobufVendored")
    ],
    targets: [
        .target(
            name: "ElizaProtoKit",
            dependencies: [
                .product(name: "SwiftProtobuf", package: "SwiftProtobufVendored")
            ]
        )
    ]
)
